// Browser history coverage keeps speed input local, records partial rounds, and preserves Claude's layout.
import {test,expect} from '@playwright/test';
import {readFile,mkdir} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
test.use({actionTimeout:15000});
test('partial speed history appears in the account and Practice starts with a new person',async({page,browserName})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.context().setExtraHTTPHeaders({'x-forwarded-for':`2001:db8::${randomUUID().slice(0,8)}`});
  expect((await page.request.get('/api/learning')).status()).toBe(401);
  const email=`history-${randomUUID()}@stanford.edu`;
  await page.goto('/');await page.getByLabel('Your Stanford email').fill(email);
  await page.getByRole('button',{name:'Email me a sign-in link'}).click();
  await expect(page.getByRole('heading',{name:'Check your inbox.'})).toBeVisible();
  const lines=(await readFile('/tmp/gsb-test-mail.jsonl','utf8')).trim().split('\n').map(line=>JSON.parse(line));
  await page.goto(lines.reverse().find(l=>l.email===email).url);
  await page.getByRole('button',{name:'Continue to Classmates'}).click();
  await page.getByLabel('Nickname',{exact:true}).fill('History learner');
  await page.getByRole('button',{name:'Save nickname'}).click();
  const prepared=page.waitForResponse(r=>r.url().endsWith('/api/sprint/prepare')&&r.ok());
  await page.getByRole('button',{name:'Play a speed round'}).click();
  const round=await(await prepared).json();
  await page.getByRole('button',{name:'Start the clock'}).click();
  await expect(page.locator('.sprint-play')).toBeVisible();
  const first=round.questions[0],second=round.questions[1];
  await page.locator('.sprint-play .answer').nth((Number(first.correctChoice)+1)%4).click();
  await expect(page.locator('.sprint-play')).toHaveAttribute('data-question-id',second.id);
  await page.locator('.sprint-play .answer').nth(Number(second.correctChoice)).click();
  await expect(page.locator('.sprint-play')).toHaveAttribute('data-question-id',round.questions[2].id);
  const checkpoint=page.waitForResponse(r=>r.url().endsWith('/api/sprint/history')&&r.ok(),{timeout:15000});
  await page.getByRole('button',{name:'Leave round',exact:true}).click();
  await checkpoint;
  await page.getByRole('button',{name:'Edit nickname for History learner',exact:true}).click();
  await page.getByText('Your face history',{exact:true}).click();
  await expect(page.getByText('3 of 24 classmates played. 21 still new.',{exact:true})).toBeVisible();
  await expect(page.getByText('1 right out of 2 answered.',{exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Most missed'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Most right'})).toBeVisible();
  const summary=await(await page.request.get('/api/learning')).json();
  expect(summary.faces.filter(f=>f.seen)).toHaveLength(3);
  expect(summary.faces.reduce((n,f)=>n+f.attempts,0)).toBe(2);
  await mkdir(`output/gsb-screenshots/${browserName}`,{recursive:true});
  await page.screenshot({path:`output/gsb-screenshots/${browserName}/face-history-phone.png`,fullPage:true});
  await page.setViewportSize({width:1366,height:900});
  await page.screenshot({path:`output/gsb-screenshots/${browserName}/face-history-desktop.png`,fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:'Save nickname'}).click();
  await expect(page.getByRole('heading',{name:'Names worth knowing.'})).toBeVisible();
  await page.getByRole('button',{name:'Practice the class deck',exact:true}).click();
  await expect(page.locator('.question .answer')).toHaveCount(4);
  const review=page.waitForResponse(r=>r.url().endsWith('/api/progress')&&r.request().method()==='POST'&&r.ok());
  await page.locator('.question .answer').first().click();
  const personId=(await review).request().postDataJSON().personId;
  expect(summary.faces.find(f=>f.id===personId).seen).toBe(0);
  expect(errors).toEqual([]);
});
